import "./globals.css";
import Footer from "../components/footer/footer";
import Navbar from "../components/navbar/navbar";
import { ThemeProvider } from "../../Context/ThemeContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container">
        <ThemeProvider>
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
